{{- if .Values.storageClass.create -}}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor
parameters:
  repl: "1"
  protocol: "nvmf"
  ioTimeout: "60"
  local: "true"
provisioner: io.openebs.csi-mayastor
volumeBindingMode: WaitForFirstConsumer
{{ end }}
