{{- if .Values.storageClass.create -}}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor-2
parameters:
  repl: "2"
  protocol: "nvmf"
  ioTimeout: "60"
  local: "true"
provisioner: io.openebs.csi-mayastor
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
{{ end }}
