{{- if .Values.rbac.enabled -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.mayastor.io_engine.serviceAccountName }}-cluster-role
rules:
  # must create mayastor pools
  - apiGroups: ["openebs.io"]
    resources: ["mayastorpools"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.mayastor.io_engine.serviceAccountName }}-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.mayastor.io_engine.serviceAccountName | quote }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.mayastor.io_engine.serviceAccountName }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
