{{- if .Values.rbac.enabled -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mayastor-daemonset-cluster-role
rules:
  # must create mayastor pools
  - apiGroups: ["openebs.io"]
    resources: ["mayastorpools"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mayastor-daemonset-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: mayastor-daemonset-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: mayastor-daemonset-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
