#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

NAMESPACE="ingress"

echo "Disabling Ingress"

"$SNAP/microk8s-helm.wrapper" uninstall ingress-nginx -n $NAMESPACE > /dev/null 2>&1
use_addon_manifest ingress/ingress-class delete
"$SNAP/microk8s-kubectl.wrapper" delete namespace $NAMESPACE

echo "Ingress is disabled"
