#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

NAMESPACE="ingress"

echo "Enabling Ingress"

CERT_SECRET=
DISABLE_VALIDATING_ADMISSION=
INGRESS_NGINX_VALUES=
INGRESS_NGINX_VERSION=
while [ $# -ge 1 ]; do
  case $1 in
    --default-ssl-certificate=*)
      CERT_SECRET="${1#*=}"
      echo "Setting ${CERT_SECRET} as the default ingress certificate"
      shift
      ;;
    --disable-validating-admission-controller)
      DISABLE_VALIDATING_ADMISSION=1
      shift
      ;;
    --values=*)
      INGRESS_NGINX_VALUES="${1#*=}"
      shift
      ;;
    -h|--help)
      echo "Options:"
      echo " -h, --help                                 Show this help"
      echo " --default-ssl-certificate=<secret>         Secret containing a SSL certificate to be used by the default HTTPS server (catch-all). Takes the form \"namespace/name\""
      echo " --disable-validating-admission-controller  Disable the validating admission webhook"
      echo " --values                                   Set custom Helm values"
      exit 0
      ;;
    *)
      echo "Unknown option ${1}" >&2
      exit 1
      ;;
  esac
done

HELM_OPTS=
if [ -n "${INGRESS_NGINX_VALUES}" ]; then
  HELM_OPTS+="--values ${INGRESS_NGINX_VALUES} "
fi
if [ -n "${CERT_SECRET}" ]; then
  HELM_OPTS+="--set controller.extraArgs.default-ssl-certificate=${CERT_SECRET} "
fi
if [ -n "${DISABLE_VALIDATING_ADMISSION}" ]; then
  HELM_OPTS+="--set controller.admissionWebhooks.enabled=false "
fi

"${SNAP}/microk8s-helm3.wrapper" upgrade --install ingress-nginx ${CURRENT_DIR}/chart \
  --namespace $NAMESPACE --create-namespace \
  --set controller.extraArgs.publish-status-address=127.0.0.1 \
  --set controller.hostPort.enabled=true \
  --set controller.ingressClass=public \
  --set controller.ingressClassResource.name=public \
  --set controller.ingressClassResource.default=true \
  --set controller.kind=DaemonSet \
  --set controller.metrics.enabled=true \
  --set controller.publishService.enabled=false \
  --set controller.service.type=ClusterIP \
  ${HELM_OPTS}

# Creating an additional public IngressClass to stay backward-compatible
use_addon_manifest ingress/ingress-class apply

echo "Ingress is enabled"
