#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

REPO="https://traefik.github.io/charts"
CHART_VERSION="37.4.0" # contains v3.6.2
GW_VERSION="v1.4.0"

ENABLE="$SNAP/microk8s-enable.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"
KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"

$HELM repo add traefik $REPO
$HELM repo update

$HELM install traefik traefik/traefik --version $CHART_VERSION -f values.yaml --wait

$KUBECTL apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/$GW_VERSION/standard-install.yaml


echo "Ingress is enabled and Gateway API is applied"
