apiVersion: v2
name: mayastor-aio
description: A Helm chart to deploy zero-ops Mayastor to a Kubernetes cluster

type: application
version: 2.0.0-microk8s-1

appVersion: "2.0.0-microk8s-1"

dependencies:
  - name: etcd-operator
    version: 0.0.1
    repository: https://raw.githubusercontent.com/canonical/etcd-operator/master/chart
  # TODO(neoaggelos): Replace this with repository after upstream release of our changes
  - name: mayastor
    version: 2.0.0-microk8s-1
    repository: https://github.com/canonical/mayastor-extensions/releases/download/v2.0.0-microk8s-1
