#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Disabling MetalLB"
KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"

$KUBECTL delete -f $CURRENT_DIR/crd.yaml

$KUBECTL delete namespaces metallb-system

echo "MetalLB is terminated"