#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

KUBECTL="$SNAP/microk8s-kubectl.wrapper"

echo "Enabling MetalLB"

ALLOWESCALATION=false
if grep  -e ubuntu /proc/version | grep 16.04 &> /dev/null
then
  ALLOWESCALATION=true
fi

read -ra ARGUMENTS <<< "$1"
if [ -z "${ARGUMENTS[@]}" ]
then
  read -p "Enter each IP address range delimited by comma (e.g. '10.64.140.43-10.64.140.49,192.168.0.105-192.168.0.111'): " ip_range_input
  if [ -z "${ip_range_input}" ]
  then
    echo "You have to input an IP Range value when asked, or provide it as an argument to the enable command, eg:"
    echo "  microk8s enable metallb:10.64.140.43-10.64.140.49,192.168.0.105-192.168.0.111"
    echo "You can also use CIDR notation, eg."
    echo "  microk8s enable metallb:192.168.1.240/24"
    exit 1
  fi
else
  ip_range_input="${ARGUMENTS[@]}"
fi
REGEX_IPV4_RANGE='^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*-[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$'
REGEX_IPV4_CIDR='^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9]{1,3}\/[0-9]{1,3}$'
REGEX_IPV6_RANGE='^(([0-9a-fA-F]{1,4}:){1,7}((([0-9a-fA-F]{1,4})?(:[0-9a-fA-F]{1,4}){1,6})|:))-(([0-9a-fA-F]{1,4}:){1,7}((([0-9a-fA-F]{1,4})?(:[0-9a-fA-F]{1,4}){1,6})|:))$'
REGEX_IPV6_CIDR='^(([0-9a-fA-F]{1,4}:){1,7}((([0-9a-fA-F]{1,4})?(:[0-9a-fA-F]{1,4}){1,6})|:))\/[0-9]{1,3}$'
ip_ranges=(`echo $ip_range_input | sed 's/,/\n/g'`)
ip_range_str="addresses:"
for ip_range in "${ip_ranges[@]}"
do
  if [[ $ip_range =~ $REGEX_IPV4_RANGE ||  $ip_range =~ $REGEX_IPV4_CIDR || $ip_range =~ $REGEX_IPV6_RANGE ||  $ip_range =~ $REGEX_IPV6_CIDR ]]
  then
    ip_range_str="${ip_range_str}\n      - ${ip_range}"
  else
    echo "Your input value ($ip_range) is not a valid IP Range"
    exit 1
  fi
done
echo "Applying Metallb manifest"
$KUBECTL apply -f $CURRENT_DIR/crd.yaml

cat $CURRENT_DIR/metallb.yaml | $SNAP/bin/sed "s@{{allow_escalation}}@$ALLOWESCALATION@g" | $KUBECTL apply -f -

echo "Waiting for Metallb controller to be ready."
while ! $KUBECTL -n metallb-system  wait deployment controller --for condition=Available=True --timeout=30s ; do
  echo "MetalLB controller is still not ready"
  sleep 1
done

while ! cat $CURRENT_DIR/addresspool.yaml | $SNAP/bin/sed "s@{{addresses}}@$ip_range_str@g" | $KUBECTL apply -f - ; do
  echo "Failed to create default address pool, will retry"
  sleep 1
done

echo "MetalLB is enabled"
