#!/usr/bin/env python3

import os
import pathlib
import subprocess

import click

SNAP = pathlib.Path(os.getenv("SNAP") or "/snap/microk8s/current")
KUBECTL = SNAP / "microk8s-kubectl.wrapper"


@click.command()
def main():
    destination_dir = "/tmp/rook"
    example_manifest_dir = destination_dir + "/deploy/examples/"
    operator_manifest = example_manifest_dir + "operator.yaml"
    crds_manifest = example_manifest_dir + "crds.yaml"
    common_manifest = example_manifest_dir + "common.yaml"

    # Delete the CRDs, common and operator
    subprocess.run([KUBECTL, "delete", "-f", crds_manifest, "-f", common_manifest, "-f", operator_manifest])


if __name__ == "__main__":
    main()
