#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "DEPRECIATION WARNING: 'prometheus' is deprecated and will soon be removed. Please use 'observability' instead."
echo ""

"$SNAP/microk8s-enable.wrapper" observability $1
