#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "Enabling RBAC"

echo "Reconfiguring apiserver"

needs_restart=false
if ! grep -q -- --authorization-mode=RBAC,Node "${SNAP_DATA}/args/kube-apiserver"; then
  needs_restart=true
fi

refresh_opt_in_config "authorization-mode" "RBAC,Node" kube-apiserver

if [ -e ${SNAP_DATA}/var/lock/clustered.lock ] || [ "$needs_restart" = "true" ]; then
  echo "Restarting apiserver"
  restart_service apiserver
fi

echo "RBAC is enabled"
