#!/bin/bash

. "${SNAP}/actions/common/utils.sh"

KUBECTL="${SNAP}/microk8s-kubectl.wrapper"

# Kube-OVN reload deployment
if ! [ -e "${SNAP_DATA}/var/lock/no-cni-reload" ] &&
   [ -e "${SNAP_DATA}/var/lock/no-flanneld" ] &&
   [ -e "${SNAP_DATA}/var/lock/cni-needs-reload" ]
then
  echo "Reloading kube-ovn"
  if (is_apiserver_ready)  &&
      "${KUBECTL}" --request-timeout 2m describe -n kube-system daemonset.apps/kube-ovn-cni &&
      "${KUBECTL}" --request-timeout 2m describe -n kube-system daemonset.apps/ovs-ovn &&
      "${KUBECTL}" --request-timeout 2m rollout restart -n kube-system daemonset.apps/kube-ovn-cni  &&
      "${KUBECTL}" --request-timeout 2m rollout restart -n kube-system daemonset.apps/ovs-ovn
  then
    rm "${SNAP_DATA}/var/lock/cni-needs-reload"
  fi
fi
