#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

echo "Disabling Dashboard"

KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
# Clean up old ingress controller resources in the default namespace, in case these are still lurking around.  
$KUBECTL delete service -n kube-system monitoring-grafana  > /dev/null 2>&1 || true
$KUBECTL delete service -n kube-system monitoring-influxdb  > /dev/null 2>&1 || true
$KUBECTL delete service -n kube-system heapster  > /dev/null 2>&1 || true

$KUBECTL delete deployment -n kube-system monitoring-influxdb-grafana-v4  > /dev/null 2>&1 || true
$KUBECTL delete deployment -n kube-system heapster-v1.5.2  > /dev/null 2>&1 || true
$KUBECTL delete clusterrolebinding heapster  > /dev/null 2>&1 || true
$KUBECTL delete configmap -n kube-system heapster-config  > /dev/null 2>&1 || true
$KUBECTL delete configmap -n kube-system eventer-config  > /dev/null 2>&1 || true
$KUBECTL delete serviceaccount -n kube-system heapster  > /dev/null 2>&1 || true 

HELM="$SNAP/microk8s-helm3.wrapper"
echo "Removing kubernetes-dashboard from kube-system namespace (backwards compatibility)"
$HELM uninstall -n kube-system kubernetes-dashboard || true
echo "Removing kubernetes-dashboard from kubernetes-dashboard namespace"
$HELM uninstall -n kubernetes-dashboard kubernetes-dashboard || true

echo "Dashboard is disabled"
