#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

REPO="https://kubernetes.github.io/dashboard/"
VERSION="7.14.0"

function usage {
  echo "Usage: microk8s enable dashboard [OPTIONS]"
  echo ""
  echo "Enable the dashboard addon."
  echo ""
  echo "   -h             Print this help message"
  echo "   -r REPOSITORY  dashboard Helm chart repository (default: ${REPO})"
  echo "   -V VERSION     dashboard Helm chart version (default: ${VERSION})"
}

while getopts ":hr:V:" arg; do
  case "${arg}" in
    V) VERSION="${OPTARG}" ;;
    r) REPO="${OPTARG}" ;;
    h)
      usage
      exit 0
      ;;
    :)
      echo "Missing argument for option -${OPTARG}"
      usage
      exit 1
      ;;
    ?)
      echo "Invalid option -${OPTARG}"
      usage
      exit 1
      ;;
  esac
done

ENABLE="$SNAP/microk8s-enable.wrapper"

echo "Enabling metrics-server"
$ENABLE metrics-server
$ENABLE helm3

HELM="$SNAP/microk8s-helm3.wrapper"

echo "Enabling Kubernetes dashboard"
$HELM upgrade --install kubernetes-dashboard kubernetes-dashboard \
  --repo "${REPO}" --version "${VERSION}" \
  --create-namespace --namespace "kubernetes-dashboard"

echo "Applying manifest"
use_addon_manifest dashboard/token-creation apply

echo "
If RBAC is not enabled access the dashboard using the token retrieved with:

microk8s kubectl describe secret -n kube-system microk8s-dashboard-token

Use this token in the https login UI of the kubernetes-dashboard service.

In an RBAC enabled setup (microk8s enable RBAC) you need to create a user with restricted
permissions as shown in:
https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
"
