#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

echo "Enabling Kubernetes Dashboard"
"$SNAP/microk8s-enable.wrapper" metrics-server
echo "Applying manifest"
use_addon_manifest dashboard/dashboard apply

echo "
If RBAC is not enabled access the dashboard by creating a default token with:

microk8s.kubectl create token -n kube-system default --duration=120m

Use this token in the https login UI of the kubernetes-dashboard service.

In an RBAC enabled setup (microk8s enable RBAC) you need to create a user with restricted
permissions as shown in:
https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
"
