#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

echo "Enabling Metrics-Server"

rm -rf $CURRENT_DIR/metrics-server-patched.yaml
if [ -e $SNAP/METRICS_SERVER_IMAGE ]
then
  METRICS_SERVER_IMAGE=$(cat $SNAP/METRICS_SERVER_IMAGE)
else
  METRICS_SERVER_IMAGE=$(cat $CURRENT_DIR/image)
fi
sed 's@${METRICS_SERVER_IMAGE}@'"${METRICS_SERVER_IMAGE}"'@g' $CURRENT_DIR/metrics-server.yaml > $CURRENT_DIR/metrics-server-patched.yaml

KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
use_addon_manifest metrics-server/metrics-server-patched apply

refresh_opt_in_config "authentication-token-webhook" "true" kubelet
restart_service kubelet

echo "Metrics-Server is enabled"
