#!/usr/bin/env python3

import click
import os
import subprocess
import yaml

regex_args='([a-zA-Z]+=[a-zA-Z0-9]+(,|))'

#apply manifest - see what goes wrong

@click.command()
@click.option('--size', default="20Gi", help="Size of the registry")
@click.option('--storageclass', default=None, help="Storage class to be used")
def enable_registry(size, storageclass):
    snap_path = os.environ.get("SNAP")
    current_path = os.path.dirname(os.path.realpath(__file__))
    # print(current_path, '======')
    manifest = "{}/registry.yaml".format(current_path)

    #Enable hostpath-storage first. If already enabled, nothing changes.
    subprocess.call(["{}/microk8s-enable.wrapper".format(snap_path), "hostpath-storage"])

    with open(manifest, "r", encoding="utf8") as f:
        docs = list(yaml.safe_load_all(f))
        docs[1].get('spec').get('resources').get('requests')['storage'] = size
        if storageclass is not None:
            docs[1].get('spec')['storageClassName'] = storageclass

    manifest_to_apply = "{}/registry_tmp.yaml".format(current_path)

    with open(manifest_to_apply, "w") as f:
        yaml.safe_dump_all(docs, f)
    # manifest_to_apply = yaml.safe_dump_all(docs)

    subprocess.call(["{}/microk8s-kubectl.wrapper".format(snap_path), "apply", "-f", manifest_to_apply])

    os.remove(manifest_to_apply)

enable_registry()