#!/bin/bash -ex

echo "Cleaning up MinIO tenants and operator"

HELM="$SNAP/microk8s-helm3.wrapper"
NAMESPACE="minio-operator"
$HELM list -n $NAMESPACE --short | xargs $HELM uninstall -n $NAMESPACE

echo "Disabled minio addon."
