#!/bin/bash -e

echo "The Minio addon is deprecated and cannot be enabled. It will be completely removed in the upcoming versions."
echo "You can run 'microk8s disable minio' to remove the minio-operator from your cluster."
