#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

snap_current=`echo "${SNAP}" | sed -e "s,${SNAP_REVISION},current,"`
${SNAP}/microk8s-addons.wrapper repo add community $snap_current/addons/community --force

echo "Community repository is now enabled"
