#!/usr/bin/env python3

import os
import socket
import subprocess
import sys
import re
from pathlib import Path
import shutil

import click

DIR = Path(__file__).absolute().parent
SNAP = Path(os.getenv("SNAP") or "/snap/microk8s/current")
SNAP_DATA = Path(os.getenv("SNAP_DATA") or "/var/snap/microk8s/current")
SNAP_COMMON = Path(os.getenv("SNAP_COMMON") or "/var/snap/microk8s/common")
HOOKS = SNAP_COMMON / "hooks"
KUBECTL = SNAP / "microk8s-kubectl.wrapper"

JSONPATH_INTERNAL_IP = 'jsonpath={.status.addresses[?(@.type=="InternalIP")].address}'

HOSTNAME = socket.gethostname()

NO_AVX_CPU_TAG = "-no-avx512"


@click.command(context_settings={"help_option_names": ["-h", "--help"]})
@click.option("--hostname", default=HOSTNAME, help="Host(s) to use for ovn-db")
@click.option("--force", is_flag=True, default=False)
def enable(hostname: str, force: bool):
    if not force:
        click.echo(
            """
Warning: this is a potentially destructive operation. Please enable kube-ovn
with:

    microk8s enable kube-ovn --force
""",
            err=True,
        )
        sys.exit(1)

    # 0. kube-ovn addon requires ha-cluster
    if not (SNAP_DATA / "var" / "lock" / "ha-cluster").exists():
        click.echo(
            """
Error: kube-ovn requires ha-cluster to be enabled. Please enable with:

    microk8s enable ha-cluster
    microk8s enable kube-ovn
""",
            err=True,
        )
        sys.exit(1)

    hosts = hostname.split(",")

    # 1. label nodes that will run ovn-db
    for host in hosts:
        stdout = subprocess.check_output(
            [KUBECTL, "get", "node", host, "-o", JSONPATH_INTERNAL_IP]
        )
        node_ip = stdout.decode().strip()

        click.echo("Label node {} ({})".format(host, node_ip))
        subprocess.check_call(
            [KUBECTL, "label", "node", host, "kube-ovn/role=master", "--overwrite"]
        )

    # 2. disable calico
    cni_yaml = SNAP_DATA / "args" / "cni-network" / "cni.yaml"
    if cni_yaml.exists():
        click.echo("Remove Calico CNI")
        subprocess.run([KUBECTL, "delete", "-f", cni_yaml])
        shutil.move(cni_yaml, SNAP_DATA / "args" / "cni-network" / "cni.yaml.backup")

    click.echo("Run kube-ovn install script")
    subprocess.check_call(["/bin/bash", DIR / "install.sh"])

    # 6. install microk8s hooks
    for hook in ["reconcile"]:
        try:
            click.echo("Install {} hook".format(hook))
            shutil.copy(DIR / "hooks" / hook, HOOKS / "{}.d".format(hook) / "10-ovn")
        except OSError as e:
            click.echo("Failed to install {} hook: {}".format(hook, e), err=True)


def cpu_has_avx_flag() -> bool:
    """
    Check if the CPU has the AVX2 or AVX512 flag.

    Returns:
        bool: True if the CPU has the AVX2 or AVX512 flag, False otherwise.
    """
    with open("/proc/cpuinfo", "r") as f:
        if re.search(r"^.*(avx[0-9]{1,3}).*$", f.read(), re.MULTILINE):
            return True

    return False


if __name__ == "__main__":
    enable()
