#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"

# Apply the dns yaml
# We do not need to see dns pods running at this point just give some slack
echo "Enabling DNS"

read -ra ARGUMENTS <<< "$1"
if [[ -z "${ARGUMENTS[@]}" ]] || [[ "${ARGS[@]}" == "/etc/resolv.conf" ]]; then
  resolv_conf="$(cat $SNAP_DATA/args/kubelet | grep -- "--resolv-conf" | tr "=" " " | gawk '{print $2}')"
  if [ ! -z "${resolv_conf}" ]; then
    # kubelet has a resolv.conf file configured, we will use that one
    echo "Using host configuration from ${resolv_conf}"
    nameserver_str="/etc/resolv.conf"
  else
    host_resolv_conf="$($SNAP/usr/bin/python3 $SNAP/scripts/find-resolv-conf.py 2> /dev/null || true)"
    if [ ! -z "${host_resolv_conf}" ]; then
      # found a host resolv.conf file with non-loopback nameservers, use that one
      echo "Using host configuration from ${host_resolv_conf}"
      refresh_opt_in_config "resolv-conf" "${host_resolv_conf}" "kubelet"
      nameserver_str="/etc/resolv.conf"
    else
      # no resolv.conf file found, fallback to Google DNS servers
      echo "No valid resolv.conf file could be found"
      echo "Falling back to 8.8.8.8 8.8.4.4 as upstream nameservers"

      nameserver_str="8.8.8.8 8.8.4.4"
    fi
  fi
else
  # validate IP addresses
  nameserver_str=""
  for ns in ${ARGUMENTS[@]//,/ }; do
    if ! "${SNAP}/bin/ip" route get "$ns" > /dev/null 2> /dev/null; then
      echo "Your input value ($ns) is not a valid and reachable IP address"
      exit 1
    fi
    nameserver_str="${nameserver_str} ${ns}"
  done
  echo "Will use ${nameserver_str} as upstream nameservers"
fi

echo "Applying manifest"
ALLOWESCALATION="false"
if grep -e ubuntu /proc/version | grep 16.04 &> /dev/null; then
  ALLOWESCALATION="true"
fi

cluster_cidr="$(get_opt_in_config '--service-cluster-ip-range' 'kube-apiserver')"
DNSIP=$(python3 -c "import ipaddress; print(ipaddress.ip_network('$cluster_cidr')[10])")

declare -A map
map[\$ALLOWESCALATION]="$ALLOWESCALATION"
map[\$NAMESERVERS]="$nameserver_str"
map[\$DNSIP]="$DNSIP"
use_addon_manifest dns/coredns apply "$(declare -p map)"
sleep 5

needs_restart=false
if ! grep -q -- --cluster-domain=cluster.local "${SNAP_DATA}/args/kubelet"; then
  needs_restart=true
elif ! grep -q -- --cluster-dns=$DNSIP "${SNAP_DATA}/args/kubelet"; then
  needs_restart=true
fi

#TODO(kjackal): do not hardcode the info below. Get it from the yaml
refresh_opt_in_config "cluster-domain" "cluster.local" kubelet
refresh_opt_in_config "cluster-dns" "$DNSIP" kubelet

if [ -e ${SNAP_DATA}/var/lock/clustered.lock ] || [ "$needs_restart" = "true" ]; then
  echo "Restarting kubelet"
  restart_service kubelet
fi

echo "DNS is enabled"
