#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

NAMESPACE="observability"
KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm.wrapper"
echo "Disabling observability"

# unload the the manifests
$HELM uninstall kube-prom-stack -n $NAMESPACE > /dev/null 2>&1
# The kubelet service is managed by Prometheus Operator, not by the chart.
# See: https://github.com/prometheus-community/helm-charts/blob/ddd351fb61030becfe855f6cce664d53b0177e4b/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L51
$KUBECTL delete service kube-prom-stack-kube-prome-kubelet -n kube-system
$HELM uninstall loki -n $NAMESPACE > /dev/null 2>&1
$HELM uninstall tempo -n $NAMESPACE > /dev/null 2>&1
$KUBECTL delete namespace $NAMESPACE

# cleanup installed CRDs.
$KUBECTL get crd | grep "\.monitoring\.coreos\.com " | cut -d' ' -f1 | xargs $KUBECTL delete crd
