#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

NAMESPACE_PTR="observability"
KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm.wrapper"
echo "Disabling observability"

# unload the the manifests
$HELM delete kube-prom-stack -n $NAMESPACE_PTR > /dev/null 2>&1
# This line below is to address an upstream bug
$KUBECTL delete service kube-prom-stack-kube-prome-kubelet -n kube-system
$HELM delete loki -n $NAMESPACE_PTR > /dev/null 2>&1
$HELM delete tempo -n $NAMESPACE_PTR > /dev/null 2>&1
$KUBECTL delete namespace $NAMESPACE_PTR
