#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

"$SNAP/microk8s-enable.wrapper" core/dns
"$SNAP/microk8s-enable.wrapper" core/helm3
"$SNAP/microk8s-enable.wrapper" core/hostpath-storage

NAMESPACE_PTR="monitoring"
KUBECTL="$SNAP/microk8s-kubectl.wrapper"

echo "Enabling observability"

# make sure the "monitoring" namespace exists
$KUBECTL create namespace "$NAMESPACE_PTR" > /dev/null 2>&1 || true
# load the CRD and wait for it to be installed
VALUES="$@"

for i in "$@"
do
case $i in
    -f=*|--values=*)
    VALUES="${i#*=}"
    shift # past argument=value
    ;;
    *)
          # unknown option
    ;;
esac
done

SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
HELM="${SNAP}/microk8s-helm3.wrapper"
$HELM repo add prometheus-community https://prometheus-community.github.io/helm-charts
$HELM repo add grafana https://grafana.github.io/helm-charts
$HELM repo update
if [ -z "$VALUES" ]
then
  $HELM upgrade --install kube-prom-stack -f ${SCRIPT_DIR}/grafana.yaml prometheus-community/kube-prometheus-stack -n $NAMESPACE_PTR
else
  $HELM upgrade --install kube-prom-stack -f ${SCRIPT_DIR}/grafana.yaml -f "$2" prometheus-community/kube-prometheus-stack -n $NAMESPACE_PTR
fi

$HELM upgrade --install loki grafana/loki-stack -n $NAMESPACE_PTR --set="grafana.sidecar.datasources.enabled=false"
$HELM upgrade --install tempo grafana/tempo -n $NAMESPACE_PTR
echo "Observability has been enabled (user/pass: admin/prom-operator)"
