#!/usr/bin/env python3

import os
import pathlib
import shutil
import subprocess
import platform
import requests

import click

DIR = pathlib.Path(__file__).parent.absolute()
PLUGINS_DIR = pathlib.Path(os.path.expandvars("$SNAP_COMMON/plugins"))
ARGS_DIR = pathlib.Path(os.path.expandvars("$SNAP_DATA/args"))
CREDS_DIR = pathlib.Path(os.path.expandvars("$SNAP_DATA/credentials"))
CERTS_DIR = pathlib.Path(os.path.expandvars("$SNAP_DATA/certs"))



def isStrict():
    """Return true if we are on a strict snap"""
    snap_yaml = pathlib.Path(os.path.expandvars("$SNAP/meta/snap.yaml"))
    with open(snap_yaml, "r") as file:
        for line_number, line in enumerate(file, start=1):
            if "confinement" in line and "strict" in line:
                return True
    return False


def FixFilePermissions():
    """Set file permissions to 600 and restrict ownership to root:root."""
    click.echo("Setting file permissions")
    try:
        dirs = [ ARGS_DIR, CREDS_DIR, CERTS_DIR ]
        if not isStrict():
            service = "/etc/systemd/system/snap.microk8s.daemon-kubelite.service"
            dirs.extend([service])
        for p in dirs:
            subprocess.call(f"chmod -R g-wr {p}".split())
            subprocess.call(f"chmod -R o-wr {p}".split())
            subprocess.call(f"chown -R root:root {p}".split())
    except subprocess.CalledProcessError as e:
        click.echo(f"Failed to set file permissions: {e}", err=True)
        exit(3)


def addArgument(arg: str, value: str, service: str):
    """
    Add argument to a service.

        Parameters:
            arg (str): arguments
            value (str): value for the argument
            service (str): name of the service to add the argument to

        Returns:
            restart (bool): should the service be restarted
    """
    exists = False
    restart = False
    with open(ARGS_DIR / service, "r") as file:
        for line_number, line in enumerate(file, start=1):
            if arg in line:
                exists = True
                break
    if not exists:
        with open(ARGS_DIR / service, "a+") as file_object:
            file_object.write(f"{arg}={value}\n")
            restart = True
    return restart


def SetServiceArguments():
    """Set arguments to all services for CIS hardening."""
    click.echo("Setting API server arguments")
    args = [("--kubelet-certificate-authority", "${SNAP_DATA}/certs/ca.crt"),
            ("--enable-admission-plugins", "EventRateLimit,AlwaysPullImages,NodeRestriction"),
            ("--admission-control-config-file", "${SNAP_DATA}/args/admission-control-config-file.yaml"),
            ("--audit-log-path", "/var/log/apiserver/audit.log"),
            ("--audit-log-maxage", "30"),
            ("--audit-log-maxbackup", "10"),
            ("--audit-log-maxsize", "100"),
            ("--audit-policy-file", "${SNAP_DATA}/args/audit-policy.yaml"),
            ("--request-timeout", "300s"),
            ("--tls-cipher-suites", "TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384"),
        ]

    restart = False
    for arg in args:
        res = addArgument(arg[0], arg[1], "kube-apiserver")
        restart = restart or res

    click.echo("Setting controller manager arguments")
    args = [("--terminated-pod-gc-threshold", "10")]

    for arg in args:
        res = addArgument(arg[0], arg[1], "kube-controller-manager")
        restart = restart or res

    click.echo("Setting kubelet arguments")
    args = [("--protect-kernel-defaults", "true"),
            ("--event-qps", "0"),
            ("--tls-cipher-suites", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"),
            ("--authorization-mode", "Webhook"),
            ("--tls-cert-file", "${SNAP_DATA}/certs/kubelet.crt"),
            ("--tls-private-key-file", "${SNAP_DATA}/certs/kubelet.key"),
        ]

    for arg in args:
        res = addArgument(arg[0], arg[1], "kubelet")
        restart = restart or res

    if restart:
        try:
            subprocess.call("snapctl services microk8s.daemon-kubelite".split())
        except subprocess.CalledProcessError as e:
            click.echo(f"Failed to restart kubelite: {e}", err=True)
            exit(4)


def EnableRBAC():
    """Enable RBAC addon."""
    click.echo("Enabling RBAC")
    try:
        microk8s_enable = os.path.expandvars("$SNAP/microk8s-enable.wrapper")
        subprocess.call(f"{microk8s_enable} rbac".split())
    except subprocess.CalledProcessError as e:
        click.echo(f"Failed to enable RBAC: {e}", err=True)
        exit(5)


def NeedsRoot():
    """Require we run the script as root (sudo)."""
    if os.geteuid() != 0:
        click.echo("Elevated permissions are needed for this addon.", err=True)
        click.echo("Please try again, this time using 'sudo'.", err=True)
        exit(1)


def CopyExtraConfigFiles():
    """Move the extra configuration files under the args directory."""
    click.echo("Copy extra files")
    for f in [ "admission-control-config-file.yaml", "eventconfig.yaml", "audit-policy.yaml"]:
        shutil.copyfile(DIR / f, ARGS_DIR / f )


def DownloadKubebench(kubebench_version: str):
    """Download kube-bench and place the wrapper script under plugins."""
    click.echo("Downloading kube-bench")
    try:
        tmpdir = pathlib.Path(os.path.expandvars("$SNAP_DATA")) / "var" / "tmp"
        tarbin = pathlib.Path(os.path.expandvars("$SNAP")) / "bin" / "tar"
        shutil.rmtree(tmpdir, ignore_errors=True)
        if not os.path.exists(tmpdir):
            os.makedirs(tmpdir)
        arch = get_arch()
        url = f"https://github.com/aquasecurity/kube-bench/releases/download/v{kubebench_version}/kube-bench_{kubebench_version}_linux_{arch}.tar.gz"
        response = requests.get(url)
        tarball = tmpdir / "kube-bench.tar.gz"
        kubebench = DIR / "tmp"
        open(tarball, "wb").write(response.content)
        if not os.path.exists(kubebench):
            os.mkdir(kubebench)
        subprocess.check_call(f"{tarbin} -vzxf {tarball}  --no-same-owner -C {kubebench}".split())
        src = DIR / "kube-bench"
        dst = PLUGINS_DIR / "kube-bench"
        shutil.copyfile(src, dst)
        subprocess.check_call(f"chmod +x {dst}".split())
    except subprocess.CalledProcessError as e:
        click.echo(f"Failed to download kube-bench: {e}", err=True)
        exit(2)


def get_arch():
    """Returns the architecture we are running on."""
    arch_translate = {"aarch64": "arm64", "x86_64": "amd64"}
    return arch_translate[platform.machine()]


def MarkAddonEnabled():
    """Mark the addon as enabled by creating a lock file."""
    lockfile = pathlib.Path(os.path.expandvars("$SNAP_DATA/var/lock/cis-hardening"))
    pathlib.Path(lockfile).touch()


def PrintExitMessage(install_kubebench):
    """Print info at the end of enabling the addon."""
    click.echo()
    click.echo("CIS hardening configuration has been applied. All microk8s commands require sudo from now on.")
    click.echo("Remember to enable this addon on nodes joining the custer.")
    if install_kubebench:
        click.echo("Inspect the CIS benchmark results with:")
        click.echo()
        click.echo("  sudo microk8s kube-bench")
    click.echo()


@click.command()
@click.option("--kubebench-version", default="0.6.13")
@click.option("--install-kubebench", default=True)
def main(kubebench_version: str, install_kubebench):
    """
    The entry point to the enable script.

        Parameters:
            kubebench_version (str): the version of kubebench we want to install
    """
    NeedsRoot()
    EnableRBAC()
    CopyExtraConfigFiles()
    if install_kubebench:
        DownloadKubebench(kubebench_version)
    FixFilePermissions()
    SetServiceArguments()
    MarkAddonEnabled()
    PrintExitMessage(install_kubebench)


if __name__ == '__main__':
    main()
