#!/bin/bash

${SNAP_COMMON}/addons/core/addons/cis-harden/tmp/kube-bench --version cis-1.24-microk8s --config ${SNAP_COMMON}/addons/core/addons/cis-harden/cfg/config.yaml --config-dir ${SNAP_COMMON}/addons/core/addons/cis-harden/cfg/ $*
