#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "Enabling Helm 3"

if [ ! -f "${SNAP_DATA}/bin/helm3" ]
then
  SOURCE_URI="https://get.helm.sh"
  HELM_VERSION="v3.8.0"

  echo "Fetching helm version $HELM_VERSION."
  run_with_sudo mkdir -p "${SNAP_DATA}/tmp/helm3"
  (cd "${SNAP_DATA}/tmp/helm3"
  fetch_as $SOURCE_URI/helm-$HELM_VERSION-linux-${SNAP_ARCH}.tar.gz "$SNAP_DATA/tmp/helm3/helm.tar.gz"
  run_with_sudo gzip -f -d "$SNAP_DATA/tmp/helm3/helm.tar.gz"
  run_with_sudo tar --no-same-owner -xf "$SNAP_DATA/tmp/helm3/helm.tar")

  run_with_sudo mkdir -p "$SNAP_DATA/bin/"
  run_with_sudo mv "$SNAP_DATA/tmp/helm3/linux-${SNAP_ARCH}/helm" "$SNAP_DATA/bin/helm3"
  run_with_sudo chmod +x "$SNAP_DATA/bin/"
  run_with_sudo chmod +x "$SNAP_DATA/bin/helm3"

  run_with_sudo rm -rf "$SNAP_DATA/tmp/helm3"
fi

echo "Helm 3 is enabled"
