name: Lint Code

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-setuptools
          sudo pip3 install black codespell
          sudo snap install node --classic
          sudo npm install --save-dev --save-exact -g prettier
      - name: Check Python formatting
        run: |
          set -eux
          black --check .
          codespell --ignore-words-list="aks,keypair" --quiet-level=2
      - name: Check YAML formatting
        run: |
          set -eux
          prettier --check **/*.yaml
