name: cla-check

on:
  pull_request:
    branches: [1.28]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@1.2.0
