---
apiVersion: etcd.database.coreos.com/v1beta3
kind: EtcdCluster
metadata:
  name: mayastor-etcd
  namespace: mayastor
spec:
  size: 3
  limitSizeToMaxReadyNodes: true
  version: "3.5.2"
  pod:
    restartPolicy: Always
    hostPathVolume: /var/snap/microk8s/common/mayastor/etcd/$NAME
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: etcd_cluster
                  operator: In
                  values: [mayastor-etcd]
            topologyKey: kubernetes.io/hostname
